config/routes.rb
Reddit::Application.routes.draw do


  devise_for :users

  resources :posts do
  	member do
  		put 'like', to: 'posts#upvote'
  		put 'dislike', to: 'posts#downvote'
  	end
  end

  root to: 'posts#index'
end

app/models/post.rb
class Post < ActiveRecord::Base
	acts_as_votable
	belongs_to :user
	
end

app/models/user.rb
class User < ActiveRecord::Base
	
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
    has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :find_post, only: [:edit, :show, :update, :destroy]
	before_filter :authenticate_user!, except: [:index, :show]


	def index
		@posts = Post.all.order("created_at DESC")
	end

	def new
		@post = current_user.posts.build
	end

	def edit
	end

	def create
		@post = current_user.posts.build(post_params)
		if @post.save
			redirect_to @post, notice: "Successfully created new post"
		else
			render 'new'
		end
	end

	def show
	end

	def destroy
		@post.destroy
		redirect_to root_path, notice: "Successfully deleted post"
	end

	def update
		if @post.update(post_params)
			redirect_to @post
		else
			render 'edit'
		end
	end

	def upvote
		@post = Post.find(params[:id])
		@post.upvote_by current_user
		redirect_to :back
	end

	def downvote
		@post = Post.find(params[:id])
		@post.downvote_by current_user
		redirect_to :back
	end


	private
	def find_post
		@post = Post.find(params[:id])
	end

	def post_params
		params.require(:post).permit(:title, :desc)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reddit</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>


  <header class="navbar navbar-default" role="navigation">
    <div class="navbar-inner">
      <div class="container">
        <div id="logo" class="navbar-brand"><%= link_to "Raddit", root_path %></div>
        <nav class="collapse navbar-collapse navbar-ex1-collapse">
        	<% if user_signed_in? -%>
						<ul class="nav navbar-nav navbar-right">
							<li><%= link_to 'Submit link', new_post_path %></li>
							<li><%= link_to 'Account', edit_user_registration_path %></li>
							<li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
						</ul>
				<% else -%>
						<ul class="nav navbar-nav pull-right">
							<li><%= link_to 'Sign up', new_user_registration_path %></li>
							<li><%= link_to 'Sign in', new_user_session_path %></li>
						</ul>
			<% end -%>
        </nav>
      </div>
    </div>
  </header>

  <div id="main_content" class="container">
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>

			<div id="content" class="col-md-9 center-block">
				<%= yield %>
			</div>
		</div>
	</div>


</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
	<div class="form-group">
		<%= f.label :Title %>
		<%= f.text_field :title, autofocus: true, class: "form-control", required: true %>
	</div>
	<br>

	<div class="form-group">
		<%= f.label :Description %>
		<%= f.text_field :desc, autofocus: true, class: "form-control", required: true %>
	</div>
		<br>

	<div class="form-group btn-group">
		<%= f.submit "Submit" , class: "btn btn-success" %>
		<%= link_to 'Cancel', root_path, class: "btn btn-primary" %>
	</div>
	
<% end %>

app/views/posts/edit.html.erb
<h1>Post</h1>

<%= render 'form' %>

<%= link_to 'Back', post_path(@post) %>

app/views/posts/index.html.erb
<% @posts.each do |f| %>
	<div class="link row clearfix">
		
		<h2><%= link_to f.title.titleize, post_path(f) %><br>
			<small class="author">Submitted <%= time_ago_in_words(f.created_at) %> ago by <b><%= f.user.email %></b></small>

		</h2>
		<br>
	

	<div class="btn-group" style="float:right">
		<%= link_to like_post_path(f), method: :put, class: "btn btn-default btn-sm" do %>
			<span class="glyphicon glyphicon-chevron-up">

			</span>
			Upvote
			<%= f.get_upvotes.size %>
		<% end %>

		<%= link_to dislike_post_path(f), method: :put, class: "btn btn-default btn-sm" do %>
			<span class="glyphicon glyphicon-hand-down">

			</span>
			Downvote
			<%= f.get_downvotes.size %>
		<% end %>
		

		<br>

	</div>
	<br><br>
	<hr>

	</div>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<div class="page-header clearfix">
	<h1><a href="" style="decoration: none"><%= @post.title.titleize %></a> <br><small style="font-size:40% ">Submitted by <b><%= @post.user.email %></b></small> </h1>


	<div class="btn-group" style="padding-left: 50px;float:right">


		<% if @post.user == current_user %>

			<%= link_to 'Delete', @post, method: :delete, data: { confirm:'are you sure?'},class: "btn btn-danger" %>
			<%= link_to 'Edit', edit_post_path(@post), class: "btn btn-default" %>
		<% else %>

			<div>
				<%= link_to 'Delete', @post, method: :delete, data: { confirm:'are you sure?'},class: "btn btn-danger disabled" %>
				<%= link_to 'Edit', edit_post_path(@post), class: "btn btn-default disabled" %>

			</div>
		<% end %>
	</div>


	<h3 ><%= @post.desc %></h3>



	<%= link_to 'Back', root_path, class: "btn btn-primary" %>
		
	
	<div class="btn-group" style="float: right">
		<%= link_to like_post_path(@post), method: :put, class: "btn btn-default btn-sm" do %>
			<span class="glyphicon glyphicon-chevron-up">

			</span>
			Upvote
			<%= @post.get_upvotes.size %>
		<% end %>

		<%= link_to dislike_post_path(@post), method: :put, class: "btn btn-default btn-sm" do %>
			<span class="glyphicon glyphicon-hand-down">

			</span>
			Downvote
			<%= @post.get_downvotes.size %>
		<% end %>
		


	</div>


	
</div>

	
		